require("jacob.plugins.lazy").setup({
	require("jacob.plugins.tokyonight"),
	require("jacob.plugins.aura"),
	require("jacob.plugins.nightfox"),
	require("jacob.plugins.oxocarbon"),
  require("jacob.plugins.oldworld"),
  require("jacob.plugins.vague"),
	require("jacob.plugins.lualine"),
	require("jacob.plugins.telescope"),
	require("jacob.plugins.treesitter"),
	-- require("jacob.plugins.treesitter-textobjects"),
	-- require("jacob.plugins.indent-blankline"),
	require("jacob.plugins.trevj"),
	require("jacob.plugins.tabline"),
	require("jacob.plugins.lsp"),
	-- require("jacob.plugins.nvim-cmp"),
	require("jacob.plugins.blink"),
	-- require("jacob.plugins.neotest"),
	require("jacob.plugins.comment"),
	require("jacob.plugins.harpoon"),
	require("jacob.plugins.slim"),
	require("jacob.plugins.eunuch"),
  require("jacob.plugins.dressing"),
  require("jacob.plugins.dispatch"),
  require("jacob.plugins.elm"),
  require("jacob.plugins.angry"),
  require("jacob.plugins.surround"),
  require("jacob.plugins.other"),
  require("jacob.plugins.abolish"),
  require("jacob.plugins.arrow"),
  require("jacob.plugins.oil"),
  require("jacob.plugins.rust-lang"),
  require("jacob.plugins.rustacean"),
  require("jacob.plugins.neogit"),
  require("jacob.plugins.blame"),
  require("jacob.plugins.gitportal"),
  require("jacob.plugins.ast-grep"),
  require("jacob.plugins.noice"),
  require("jacob.plugins.mini"),
  require("jacob.plugins.rspec"),
  require("jacob.plugins.autosession"),
  require("jacob.plugins.buvvers"),
  require("jacob.plugins.overseer"),
})
